export const NEGATIVE_MESSAGES = [
  'Its was a Fortnite',
  'Its was a mistake',
  'Miss click',
  'You lose',
  'Ты наугад отвечаешь?',
  'Это же легко',
  'NOPE',
  '*Тебе прострелили колено*',
  'You died',
  'Подумай головой! Тебе же яйца отрезали, а не мозги!',
  'Snake? Snake!? Snaaaaaaaake!',
  'Cake is a lie',
  'Прости, Джо в сделку не входил',
  'Спасибо Марио, но наша принцесса в другом замке!',
  'Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at 4headerd',
  'Wrong',
  'Wrong',
  'Wrong',
  'Wrong',
  'Wrong',
  'Wrong',
  'Wrong',
  'Wrong',
  'Wrong',
  'Wrong',
  'Wrong',
  'Wrong',
  'Wrong',
  'Wrong',
  'Wrong',
  'Wrong',
  'Wrong',
  'Wrong',
  'Wrong',
  'Wrong',
  'Try again',
  'Try again',
  'Try again',
  'Try again',
  'Try again',
  'Try again',
  'Try again',
  'Try again',
  'Try again'
];

export const POSITIVE_MESSAGES = [
  'Correct',
  'Correct',
  'Correct',
  'Correct',
  'Чувак, если ты можешь съесть свой хавчик в то время, когда все его теряют, ты очень крут',
  'Correct',
  'О божечки! Да это же великий Чемпион Арены!',
  'Знания - сила! Значит, я вдвое сильнее!',
  'You f*cking nerd',
  'God like',
  '1-й на сервере! Воин 80-го уровня',
  'Good one',
  'Brutality',
  'Monster kill',
  'Это было легко',
  'Побежден могучий враг',
  'Aced',
  'Well done boy',
  'Зачем нужно жрать капусту, если есть картошка?',
  'Ты молодчага'
];
